"""Stable error codes for calculation-report APIs."""

from enum import StrEnum


class CalcErrorCode(StrEnum):
    """Identify calculation-report failures independently from localized text."""

    INVALID_OBJECT_ID = "INVALID_OBJECT_ID"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_REVISION_CONFLICT = "WORKSPACE_REVISION_CONFLICT"
    WORKSPACE_INVALID = "WORKSPACE_INVALID"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    VERSION_ALREADY_EXISTS = "VERSION_ALREADY_EXISTS"
    DEPENDENCY_INVALID = "DEPENDENCY_INVALID"
    DEPENDENCY_CYCLE = "DEPENDENCY_CYCLE"
    EXECUTION_ARTIFACT_NOT_READY = "EXECUTION_ARTIFACT_NOT_READY"
    EXECUTION_ARTIFACT_BUILD_FAILED = "EXECUTION_ARTIFACT_BUILD_FAILED"
    EXECUTION_NOT_FOUND = "EXECUTION_NOT_FOUND"
    EXECUTION_PROCESS_LOST = "EXECUTION_PROCESS_LOST"
    SANDBOX_BACKEND_UNAVAILABLE = "SANDBOX_BACKEND_UNAVAILABLE"
    SHARE_NOT_FOUND = "SHARE_NOT_FOUND"
    SHARE_NOT_ALLOWED = "SHARE_NOT_ALLOWED"
    ARCHIVE_INVALID = "ARCHIVE_INVALID"
