"""initial optimized schema

Revision ID: 2f85e0c7600d
Revises:
Create Date: 2026-07-18 15:32:14.220059

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2f85e0c7600d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calc_report_artifact",
        sa.Column("artifactKind", sa.SmallInteger(), nullable=False),
        sa.Column("contentHash", sa.CHAR(length=64), nullable=False),
        sa.Column("storageKey", sa.String(length=500), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("fileCount", sa.Integer(), nullable=False),
        sa.Column("totalSize", sa.BigInteger(), nullable=False),
        sa.Column(
            "formatVersion", sa.SmallInteger(), server_default="1", nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "artifactKind IN (1, 2)",
            name=op.f("ck_calc_report_artifact_artifact_kind_values"),
        ),
        sa.CheckConstraint(
            "fileCount >= 0",
            name=op.f("ck_calc_report_artifact_file_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "formatVersion >= 1",
            name=op.f("ck_calc_report_artifact_format_version_positive"),
        ),
        sa.CheckConstraint(
            "totalSize >= 0",
            name=op.f("ck_calc_report_artifact_total_size_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_artifact")),
        sa.UniqueConstraint(
            "contentHash", name=op.f("uq_calc_report_artifact_contentHash")
        ),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_artifact_oid")),
        sa.UniqueConstraint(
            "storageKey", name=op.f("uq_calc_report_artifact_storageKey")
        ),
    )
    op.create_table(
        "department",
        sa.Column("parentId", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sortOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parentId"],
            ["department.id"],
            name=op.f("fk_department_parentId_department"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
        sa.UniqueConstraint("oid", name=op.f("uq_department_oid")),
    )
    op.create_index(
        "ix_department_parent_sort",
        "department",
        ["parentId", "sortOrder"],
        unique=False,
    )
    op.create_index(
        "uq_department_active_parent_name",
        "department",
        ["parentId", "name"],
        unique=True,
        sqlite_where=sa.text('"parentId" IS NOT NULL AND "deletedAt" IS NULL'),
        postgresql_where=sa.text('"parentId" IS NOT NULL AND "deletedAt" IS NULL'),
    )
    op.create_index(
        "uq_department_active_root_name",
        "department",
        ["name"],
        unique=True,
        sqlite_where=sa.text('"parentId" IS NULL AND "deletedAt" IS NULL'),
        postgresql_where=sa.text('"parentId" IS NULL AND "deletedAt" IS NULL'),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "readonly", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_system_settings_key")),
        sa.UniqueConstraint("oid", name=op.f("uq_system_settings_oid")),
    )
    op.create_table(
        "tmp_files",
        sa.Column("filePath", sa.String(length=500), nullable=False),
        sa.Column("expireTime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "isDeleted", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tmp_files")),
        sa.UniqueConstraint("filePath", name="uq_tmp_files_filePath"),
        sa.UniqueConstraint("oid", name=op.f("uq_tmp_files_oid")),
    )
    op.create_index(
        "ix_tmp_files_expireTime", "tmp_files", ["expireTime"], unique=False
    )
    op.create_index("ix_tmp_files_filePath", "tmp_files", ["filePath"], unique=False)
    op.create_index("ix_tmp_files_isDeleted", "tmp_files", ["isDeleted"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("nickName", sa.String(length=50), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("salt", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Integer(), server_default="1", nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN (0, 1, 2)", name=op.f("ck_users_status_values")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("oid", name=op.f("uq_users_oid")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "calc_execution_bundle",
        sa.Column("bundleHash", sa.CHAR(length=64), nullable=False),
        sa.Column("runtimeFingerprint", sa.String(length=255), nullable=False),
        sa.Column("runtimeImageDigest", sa.String(length=71), nullable=True),
        sa.Column("entrySourceArtifactId", sa.Integer(), nullable=False),
        sa.Column("entryExecutionArtifactId", sa.Integer(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column(
            "formatVersion", sa.SmallInteger(), server_default="1", nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "formatVersion >= 1",
            name=op.f("ck_calc_execution_bundle_format_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["entryExecutionArtifactId"],
            ["calc_report_artifact.id"],
            name="fk_execution_bundle_entry_execution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entrySourceArtifactId"],
            ["calc_report_artifact.id"],
            name="fk_execution_bundle_entry_source",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_execution_bundle")),
        sa.UniqueConstraint(
            "bundleHash", name=op.f("uq_calc_execution_bundle_bundleHash")
        ),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_execution_bundle_oid")),
    )
    op.create_table(
        "calc_report_artifact_build",
        sa.Column("sourceArtifactId", sa.Integer(), nullable=False),
        sa.Column("runtimeFingerprint", sa.String(length=255), nullable=False),
        sa.Column("outputArtifactId", sa.Integer(), nullable=True),
        sa.Column("status", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("diagnostics", sa.JSON(), nullable=True),
        sa.Column("attemptCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("leaseOwner", sa.String(length=128), nullable=True),
        sa.Column("leaseExpiresAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("startedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attemptCount >= 0",
            name=op.f("ck_calc_report_artifact_build_attempt_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "status != 2 OR outputArtifactId IS NOT NULL",
            name=op.f("ck_calc_report_artifact_build_ready_requires_output"),
        ),
        sa.CheckConstraint(
            "status = 1 OR (leaseOwner IS NULL AND leaseExpiresAt IS NULL)",
            name=op.f("ck_calc_report_artifact_build_lease_only_while_building"),
        ),
        sa.CheckConstraint(
            "status IN (0, 1, 2, 3)",
            name=op.f("ck_calc_report_artifact_build_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["outputArtifactId"],
            ["calc_report_artifact.id"],
            name="fk_artifact_build_output",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sourceArtifactId"],
            ["calc_report_artifact.id"],
            name="fk_artifact_build_source",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_artifact_build")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_artifact_build_oid")),
        sa.UniqueConstraint(
            "sourceArtifactId",
            "runtimeFingerprint",
            name="uq_calc_report_artifact_build_source_runtime",
        ),
    )
    op.create_index(
        "ix_calc_report_artifact_build_status_lease",
        "calc_report_artifact_build",
        ["status", "leaseExpiresAt"],
        unique=False,
    )
    op.create_table(
        "calc_report_category",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("manualOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "isPinned", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "isHidden", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("frequencyCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("agingEpoch", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lastUsedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_calc_report_category_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_category")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_category_oid")),
    )
    op.create_index(
        "ix_calc_report_category_user_deleted_sort",
        "calc_report_category",
        ["userId", "deletedAt", "isPinned", "manualOrder"],
        unique=False,
    )
    op.create_index(
        "uq_calc_report_category_active_user_name",
        "calc_report_category",
        ["userId", "name"],
        unique=True,
        sqlite_where=sa.text('"deletedAt" IS NULL'),
        postgresql_where=sa.text('"deletedAt" IS NULL'),
    )
    op.create_table(
        "calc_report_instance_category",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sortOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_calc_report_instance_category_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_instance_category")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_instance_category_oid")),
    )
    op.create_index(
        "ix_calc_report_instance_category_user_deleted_sort",
        "calc_report_instance_category",
        ["userId", "deletedAt", "sortOrder"],
        unique=False,
    )
    op.create_index(
        "uq_calc_report_instance_category_active_user_name",
        "calc_report_instance_category",
        ["userId", "name"],
        unique=True,
        sqlite_where=sa.text('"deletedAt" IS NULL'),
        postgresql_where=sa.text('"deletedAt" IS NULL'),
    )
    op.create_table(
        "department_user",
        sa.Column("departmentId", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["departmentId"],
            ["department.id"],
            name=op.f("fk_department_user_departmentId_department"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_department_user_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "departmentId", "userId", name=op.f("pk_department_user")
        ),
    )
    op.create_table(
        "user_settings",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_user_settings_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
        sa.UniqueConstraint("oid", name=op.f("uq_user_settings_oid")),
        sa.UniqueConstraint("userId", "key", name="uq_user_settings_user_key"),
    )
    op.create_table(
        "calc_execution_bundle_component",
        sa.Column("bundleId", sa.Integer(), nullable=False),
        sa.Column("componentKey", sa.String(length=160), nullable=False),
        sa.Column("scopeKey", sa.String(length=80), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=True),
        sa.Column("selectorKey", sa.String(length=32), nullable=True),
        sa.Column("sourceArtifactId", sa.Integer(), nullable=False),
        sa.Column("executionArtifactId", sa.Integer(), nullable=False),
        sa.Column("isEntry", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            '"isEntry" IS 1 AND alias IS NULL AND "selectorKey" IS NULL OR "isEntry" IS 0 AND alias IS NOT NULL AND "selectorKey" IS NOT NULL',
            name=op.f("ck_calc_execution_bundle_component_entry_dependency_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["bundleId"],
            ["calc_execution_bundle.id"],
            name="fk_bundle_component_bundle",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["executionArtifactId"],
            ["calc_report_artifact.id"],
            name="fk_bundle_component_execution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sourceArtifactId"],
            ["calc_report_artifact.id"],
            name="fk_bundle_component_source",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_execution_bundle_component")),
        sa.UniqueConstraint(
            "bundleId", "componentKey", name="uq_execution_bundle_component_key"
        ),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_execution_bundle_component_oid")),
    )
    op.create_index(
        "uq_execution_bundle_entry",
        "calc_execution_bundle_component",
        ["bundleId"],
        unique=True,
        sqlite_where=sa.text('"isEntry" IS TRUE'),
        postgresql_where=sa.text('"isEntry" IS TRUE'),
    )
    op.create_table(
        "calc_report",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("categoryId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover", sa.String(length=500), nullable=True),
        sa.Column(
            "entryPath",
            sa.String(length=255),
            server_default="src/main.py",
            nullable=False,
        ),
        sa.Column(
            "formatVersion", sa.SmallInteger(), server_default="1", nullable=False
        ),
        sa.Column(
            "workspaceRevision", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column("workspaceArtifactId", sa.Integer(), nullable=True),
        sa.Column("latestVersionId", sa.Integer(), nullable=True),
        sa.Column("originType", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("canEdit", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "canShare", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "isSystemComponent",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "formatVersion >= 1", name=op.f("ck_calc_report_format_version_positive")
        ),
        sa.CheckConstraint(
            "originType IN (1, 2, 3, 4, 5)",
            name=op.f("ck_calc_report_origin_type_values"),
        ),
        sa.CheckConstraint(
            "workspaceRevision >= 0",
            name=op.f("ck_calc_report_workspace_revision_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["categoryId"],
            ["calc_report_category.id"],
            name=op.f("fk_calc_report_categoryId_calc_report_category"),
            ondelete="RESTRICT",
        ),
        *(
            [
                sa.ForeignKeyConstraint(
                    ["id", "latestVersionId"],
                    ["calc_report_version.reportId", "calc_report_version.id"],
                    name="fk_calc_report_latest_version",
                    ondelete="RESTRICT",
                )
            ]
            if op.get_bind().dialect.name == "sqlite"
            else []
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_calc_report_userId_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspaceArtifactId"],
            ["calc_report_artifact.id"],
            name=op.f("fk_calc_report_workspaceArtifactId_calc_report_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_oid"))
    )
    op.create_index(
        "ix_calc_report_user_deleted_updated",
        "calc_report",
        ["userId", "deletedAt", "updatedAt"],
        unique=False,
    )
    op.create_index(
        "uq_calc_report_active_user_category_name",
        "calc_report",
        ["userId", "categoryId", "name"],
        unique=True,
        sqlite_where=sa.text('"deletedAt" IS NULL'),
        postgresql_where=sa.text('"deletedAt" IS NULL'),
    )
    op.create_table(
        "calc_report_dependency",
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("targetReportId", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "reportId != targetReportId",
            name=op.f("ck_calc_report_dependency_reports_differ"),
        ),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_dependency_reportId_calc_report"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["targetReportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_dependency_targetReportId_calc_report"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_dependency")),
        sa.UniqueConstraint(
            "id", "targetReportId", name="uq_calc_report_dependency_id_target_report"
        ),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_dependency_oid")),
        sa.UniqueConstraint(
            "reportId", "alias", name="uq_calc_report_dependency_report_alias"
        ),
    )
    op.create_table(
        "calc_report_sync_source",
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("sourceLocator", sa.Text(), nullable=False),
        sa.Column("sourceReportOid", sa.CHAR(length=24), nullable=False),
        sa.Column("sourceVersionName", sa.String(length=64), nullable=False),
        sa.Column("sourceArtifactHash", sa.CHAR(length=64), nullable=False),
        sa.Column("lastCheckedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lastSyncedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_sync_source_reportId_calc_report"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_sync_source")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_sync_source_oid")),
        sa.UniqueConstraint(
            "reportId", name=op.f("uq_calc_report_sync_source_reportId")
        ),
    )
    op.create_table(
        "calc_report_version",
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("sourceArtifactId", sa.Integer(), nullable=False),
        sa.Column("major", sa.Integer(), nullable=False),
        sa.Column("minor", sa.Integer(), nullable=False),
        sa.Column("patch", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("publishedByUserId", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "major >= 0", name=op.f("ck_calc_report_version_major_nonnegative")
        ),
        sa.CheckConstraint(
            "minor >= 0", name=op.f("ck_calc_report_version_minor_nonnegative")
        ),
        sa.CheckConstraint(
            "patch >= 0", name=op.f("ck_calc_report_version_patch_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["publishedByUserId"],
            ["users.id"],
            name=op.f("fk_calc_report_version_publishedByUserId_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_version_reportId_calc_report"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sourceArtifactId"],
            ["calc_report_artifact.id"],
            name=op.f("fk_calc_report_version_sourceArtifactId_calc_report_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_version")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_version_oid")),
        sa.UniqueConstraint("reportId", "id", name="uq_calc_report_version_report_id"),
        sa.UniqueConstraint(
            "reportId", "major", "minor", "patch", name="uq_calc_report_version_semver"
        ),
    )
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_calc_report_latest_version",
            "calc_report",
            "calc_report_version",
            ["id", "latestVersionId"],
            ["reportId", "id"],
            ondelete="RESTRICT",
        )
    op.create_table(
        "favorite_calc_reports",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_favorite_calc_reports_reportId_calc_report"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_favorite_calc_reports_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "userId", "reportId", name=op.f("pk_favorite_calc_reports")
        ),
    )
    op.create_table(
        "input_cache",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("entryName", sa.String(length=128), nullable=False),
        sa.Column("sourceArtifactId", sa.Integer(), nullable=False),
        sa.Column("defaults", sa.JSON(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiresAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_input_cache_reportId_calc_report"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sourceArtifactId"],
            ["calc_report_artifact.id"],
            name=op.f("fk_input_cache_sourceArtifactId_calc_report_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_input_cache_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_input_cache")),
        sa.UniqueConstraint("oid", name=op.f("uq_input_cache_oid")),
        sa.UniqueConstraint(
            "userId", "reportId", "entryName", name="uq_input_cache_user_report_entry"
        ),
    )
    op.create_table(
        "calc_execution",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("bundleId", sa.Integer(), nullable=False),
        sa.Column("sourceType", sa.SmallInteger(), nullable=False),
        sa.Column("resolvedVersionId", sa.Integer(), nullable=True),
        sa.Column("executorType", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("sandboxExecutionId", sa.String(length=64), nullable=True),
        sa.Column("executorNodeId", sa.String(length=128), nullable=True),
        sa.Column("startedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lastActiveAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiresAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resultPath", sa.String(length=500), nullable=True),
        sa.Column("errorCode", sa.String(length=64), nullable=True),
        sa.Column("errorMessage", sa.Text(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(sourceType = 1 AND resolvedVersionId IS NULL) OR (sourceType IN (2, 3) AND resolvedVersionId IS NOT NULL)",
            name=op.f("ck_calc_execution_source_version_shape"),
        ),
        sa.CheckConstraint(
            "executorType IN (1, 2)",
            name=op.f("ck_calc_execution_executor_type_values"),
        ),
        sa.CheckConstraint(
            "sourceType IN (1, 2, 3)", name=op.f("ck_calc_execution_source_type_values")
        ),
        sa.CheckConstraint(
            "status IN (0, 1, 2, 3, 4, 5)", name=op.f("ck_calc_execution_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["bundleId"],
            ["calc_execution_bundle.id"],
            name=op.f("fk_calc_execution_bundleId_calc_execution_bundle"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reportId", "resolvedVersionId"],
            ["calc_report_version.reportId", "calc_report_version.id"],
            name="fk_calc_execution_resolved_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_execution_reportId_calc_report"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_calc_execution_userId_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_execution")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_execution_oid")),
        sa.UniqueConstraint(
            "sandboxExecutionId", name=op.f("uq_calc_execution_sandboxExecutionId")
        ),
    )
    op.create_index(
        "ix_calc_execution_report_created",
        "calc_execution",
        ["reportId", "createdAt"],
        unique=False,
    )
    op.create_index(
        "ix_calc_execution_status_expires",
        "calc_execution",
        ["status", "expiresAt"],
        unique=False,
    )
    op.create_index(
        "ix_calc_execution_user_created",
        "calc_execution",
        ["userId", "createdAt"],
        unique=False,
    )
    op.create_table(
        "calc_report_dependency_selector",
        sa.Column("dependencyId", sa.Integer(), nullable=False),
        sa.Column("targetReportId", sa.Integer(), nullable=False),
        sa.Column("selectorKey", sa.String(length=32), nullable=False),
        sa.Column("targetVersionId", sa.Integer(), nullable=True),
        sa.Column(
            "isDefault", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(selectorKey = 'latest' AND targetVersionId IS NULL) OR (selectorKey != 'latest' AND targetVersionId IS NOT NULL)",
            name=op.f("ck_calc_report_dependency_selector_selector_target_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["dependencyId", "targetReportId"],
            ["calc_report_dependency.id", "calc_report_dependency.targetReportId"],
            name="fk_dependency_selector_dependency_target",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["targetReportId", "targetVersionId"],
            ["calc_report_version.reportId", "calc_report_version.id"],
            name="fk_dependency_selector_target_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_dependency_selector")),
        sa.UniqueConstraint(
            "dependencyId", "selectorKey", name="uq_dependency_selector_dependency_key"
        ),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_dependency_selector_oid")),
    )
    op.create_index(
        "uq_dependency_selector_default",
        "calc_report_dependency_selector",
        ["dependencyId"],
        unique=True,
        sqlite_where=sa.text('"isDefault" IS TRUE'),
        postgresql_where=sa.text('"isDefault" IS TRUE'),
    )
    op.create_table(
        "calc_report_origin",
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("sourceReportId", sa.Integer(), nullable=True),
        sa.Column("sourceVersionId", sa.Integer(), nullable=True),
        sa.Column("sourceArtifactId", sa.Integer(), nullable=True),
        sa.Column("sourceArchiveHash", sa.CHAR(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_origin_reportId_calc_report"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sourceArtifactId"],
            ["calc_report_artifact.id"],
            name=op.f("fk_calc_report_origin_sourceArtifactId_calc_report_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sourceReportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_origin_sourceReportId_calc_report"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sourceVersionId"],
            ["calc_report_version.id"],
            name=op.f("fk_calc_report_origin_sourceVersionId_calc_report_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_origin")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_origin_oid")),
        sa.UniqueConstraint("reportId", name=op.f("uq_calc_report_origin_reportId")),
    )
    op.create_table(
        "calc_report_instance",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("categoryId", sa.Integer(), nullable=False),
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("sourceVersionId", sa.Integer(), nullable=True),
        sa.Column("bundleId", sa.Integer(), nullable=False),
        sa.Column("executionId", sa.Integer(), nullable=True),
        sa.Column("reportName", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("defaults", sa.JSON(), nullable=False),
        sa.Column("inputWindows", sa.JSON(), nullable=False),
        sa.Column("resultPath", sa.String(length=500), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_calc_report_instance_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["bundleId"],
            ["calc_execution_bundle.id"],
            name=op.f("fk_calc_report_instance_bundleId_calc_execution_bundle"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["categoryId"],
            ["calc_report_instance_category.id"],
            name="fk_report_instance_category",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["executionId"],
            ["calc_execution.id"],
            name=op.f("fk_calc_report_instance_executionId_calc_execution"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reportId", "sourceVersionId"],
            ["calc_report_version.reportId", "calc_report_version.id"],
            name="fk_calc_report_instance_source_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reportId"],
            ["calc_report.id"],
            name=op.f("fk_calc_report_instance_reportId_calc_report"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_calc_report_instance_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_instance")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_instance_oid")),
    )
    op.create_index(
        "ix_calc_report_instance_user_deleted_updated",
        "calc_report_instance",
        ["userId", "deletedAt", "updatedAt"],
        unique=False,
    )
    op.create_table(
        "calc_report_share_link",
        sa.Column("reportId", sa.Integer(), nullable=False),
        sa.Column("versionId", sa.Integer(), nullable=False),
        sa.Column("tokenHash", sa.CHAR(length=64), nullable=False),
        sa.Column("tokenCiphertext", sa.Text(), nullable=False),
        sa.Column("accessType", sa.SmallInteger(), nullable=False),
        sa.Column("expiresAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revokedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("maxUseCount", sa.Integer(), nullable=True),
        sa.Column("useCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("canEdit", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "canShare", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("createdByUserId", sa.Integer(), nullable=False),
        sa.Column("previewExecutionId", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "accessType IN (1, 2, 3, 4)",
            name=op.f("ck_calc_report_share_link_access_type_values"),
        ),
        sa.CheckConstraint(
            "maxUseCount IS NULL OR maxUseCount >= 0",
            name=op.f("ck_calc_report_share_link_max_use_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "useCount >= 0",
            name=op.f("ck_calc_report_share_link_use_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["createdByUserId"],
            ["users.id"],
            name=op.f("fk_calc_report_share_link_createdByUserId_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["previewExecutionId"],
            ["calc_execution.id"],
            name=op.f("fk_calc_report_share_link_previewExecutionId_calc_execution"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reportId", "versionId"],
            ["calc_report_version.reportId", "calc_report_version.id"],
            name="fk_share_link_report_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_share_link")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_share_link_oid")),
        sa.UniqueConstraint(
            "tokenHash", name=op.f("uq_calc_report_share_link_tokenHash")
        ),
    )
    op.create_table(
        "user_input_history",
        sa.Column("executionId", sa.Integer(), nullable=False),
        sa.Column("defaults", sa.JSON(), nullable=False),
        sa.Column("windows", sa.JSON(), nullable=False),
        sa.Column("inputHistory", sa.JSON(), nullable=False),
        sa.Column("currentStep", sa.Integer(), server_default="0", nullable=False),
        sa.Column("totalSteps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["executionId"],
            ["calc_execution.id"],
            name=op.f("fk_user_input_history_executionId_calc_execution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_input_history")),
        sa.UniqueConstraint(
            "executionId", name=op.f("uq_user_input_history_executionId")
        ),
        sa.UniqueConstraint("oid", name=op.f("uq_user_input_history_oid")),
    )
    op.create_table(
        "calc_report_instance_share",
        sa.Column("instanceId", sa.Integer(), nullable=False),
        sa.Column("createdByUserId", sa.Integer(), nullable=False),
        sa.Column("revokedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "isEnabled", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "oid",
            sa.CHAR(length=24),
            nullable=False,
            comment="Global 24-character hexadecimal object identifier",
        ),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["createdByUserId"],
            ["users.id"],
            name=op.f("fk_calc_report_instance_share_createdByUserId_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instanceId"],
            ["calc_report_instance.id"],
            name=op.f("fk_calc_report_instance_share_instanceId_calc_report_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calc_report_instance_share")),
        sa.UniqueConstraint("oid", name=op.f("uq_calc_report_instance_share_oid")),
    )
    op.create_index(
        "ix_calc_report_instance_share_instance_revoked",
        "calc_report_instance_share",
        ["instanceId", "revokedAt"],
        unique=False,
    )
    op.create_index(
        "uq_calc_report_instance_share_active_instance",
        "calc_report_instance_share",
        ["instanceId"],
        unique=True,
        sqlite_where=sa.text('"revokedAt" IS NULL AND "isEnabled" IS TRUE'),
        postgresql_where=sa.text('"revokedAt" IS NULL AND "isEnabled" IS TRUE'),
    )
    op.create_table(
        "calc_report_share_department",
        sa.Column("shareLinkId", sa.Integer(), nullable=False),
        sa.Column("departmentId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["departmentId"],
            ["department.id"],
            name=op.f("fk_calc_report_share_department_departmentId_department"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shareLinkId"],
            ["calc_report_share_link.id"],
            name=op.f(
                "fk_calc_report_share_department_shareLinkId_calc_report_share_link"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "shareLinkId", "departmentId", name=op.f("pk_calc_report_share_department")
        ),
    )
    op.create_table(
        "calc_report_share_recipient",
        sa.Column("shareLinkId", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shareLinkId"],
            ["calc_report_share_link.id"],
            name="fk_share_recipient_link",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
            name=op.f("fk_calc_report_share_recipient_userId_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "shareLinkId", "userId", name=op.f("pk_calc_report_share_recipient")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calc_report_share_recipient")
    op.drop_table("calc_report_share_department")
    op.drop_index(
        "uq_calc_report_instance_share_active_instance",
        table_name="calc_report_instance_share",
        sqlite_where=sa.text('"revokedAt" IS NULL AND "isEnabled" IS TRUE'),
        postgresql_where=sa.text('"revokedAt" IS NULL AND "isEnabled" IS TRUE'),
    )
    op.drop_index(
        "ix_calc_report_instance_share_instance_revoked",
        table_name="calc_report_instance_share",
    )
    op.drop_table("calc_report_instance_share")
    op.drop_table("user_input_history")
    op.drop_table("calc_report_share_link")
    op.drop_index(
        "ix_calc_report_instance_user_deleted_updated",
        table_name="calc_report_instance",
    )
    op.drop_table("calc_report_instance")
    op.drop_table("calc_report_origin")
    op.drop_index(
        "uq_dependency_selector_default",
        table_name="calc_report_dependency_selector",
        sqlite_where=sa.text('"isDefault" IS TRUE'),
        postgresql_where=sa.text('"isDefault" IS TRUE'),
    )
    op.drop_table("calc_report_dependency_selector")
    op.drop_index("ix_calc_execution_user_created", table_name="calc_execution")
    op.drop_index("ix_calc_execution_status_expires", table_name="calc_execution")
    op.drop_index("ix_calc_execution_report_created", table_name="calc_execution")
    op.drop_table("calc_execution")
    op.drop_table("input_cache")
    op.drop_table("favorite_calc_reports")
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint(
            "fk_calc_report_latest_version", "calc_report", type_="foreignkey"
        )
    op.drop_table("calc_report_version")
    op.drop_table("calc_report_sync_source")
    op.drop_table("calc_report_dependency")
    op.drop_index(
        "uq_calc_report_active_user_category_name",
        table_name="calc_report",
        sqlite_where=sa.text('"deletedAt" IS NULL'),
        postgresql_where=sa.text('"deletedAt" IS NULL'),
    )
    op.drop_index("ix_calc_report_user_deleted_updated", table_name="calc_report")
    op.drop_table("calc_report")
    op.drop_index(
        "uq_execution_bundle_entry",
        table_name="calc_execution_bundle_component",
        sqlite_where=sa.text('"isEntry" IS TRUE'),
        postgresql_where=sa.text('"isEntry" IS TRUE'),
    )
    op.drop_table("calc_execution_bundle_component")
    op.drop_table("user_settings")
    op.drop_table("department_user")
    op.drop_index(
        "uq_calc_report_instance_category_active_user_name",
        table_name="calc_report_instance_category",
        sqlite_where=sa.text('"deletedAt" IS NULL'),
        postgresql_where=sa.text('"deletedAt" IS NULL'),
    )
    op.drop_index(
        "ix_calc_report_instance_category_user_deleted_sort",
        table_name="calc_report_instance_category",
    )
    op.drop_table("calc_report_instance_category")
    op.drop_index(
        "uq_calc_report_category_active_user_name",
        table_name="calc_report_category",
        sqlite_where=sa.text('"deletedAt" IS NULL'),
        postgresql_where=sa.text('"deletedAt" IS NULL'),
    )
    op.drop_index(
        "ix_calc_report_category_user_deleted_sort", table_name="calc_report_category"
    )
    op.drop_table("calc_report_category")
    op.drop_index(
        "ix_calc_report_artifact_build_status_lease",
        table_name="calc_report_artifact_build",
    )
    op.drop_table("calc_report_artifact_build")
    op.drop_table("calc_execution_bundle")
    op.drop_table("users")
    op.drop_index("ix_tmp_files_isDeleted", table_name="tmp_files")
    op.drop_index("ix_tmp_files_filePath", table_name="tmp_files")
    op.drop_index("ix_tmp_files_expireTime", table_name="tmp_files")
    op.drop_table("tmp_files")
    op.drop_table("system_settings")
    op.drop_index(
        "uq_department_active_root_name",
        table_name="department",
        sqlite_where=sa.text('"parentId" IS NULL AND "deletedAt" IS NULL'),
        postgresql_where=sa.text('"parentId" IS NULL AND "deletedAt" IS NULL'),
    )
    op.drop_index(
        "uq_department_active_parent_name",
        table_name="department",
        sqlite_where=sa.text('"parentId" IS NOT NULL AND "deletedAt" IS NULL'),
        postgresql_where=sa.text('"parentId" IS NOT NULL AND "deletedAt" IS NULL'),
    )
    op.drop_index("ix_department_parent_sort", table_name="department")
    op.drop_table("department")
    op.drop_table("calc_report_artifact")
    # ### end Alembic commands ###
