FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install --yes --no-install-recommends docker.io \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/uzoncalc
COPY src/core ./src/core
COPY src/api ./src/api
RUN pip install --no-cache-dir ./src/core ./src/api

WORKDIR /opt/uzoncalc/src/api
CMD ["python", "-m", "app.sandbox.sandbox_server"]
