"""Runtime support for executable UzonCalc v4 archives."""

from __future__ import annotations

import ast
import importlib
import importlib.util
import runpy
import sys
import tempfile
from pathlib import Path
from types import ModuleType
from typing import Any

from .. import view
from ..handcalc.preinstrument import _CalcdepsImportRewriter
from ..workspace_imports import rewrite_workspace_source, workspace_import_roots

from .cli_workspace_archive import ARCHIVE_MAIN_PATH, read_workspace_archive


def run_workspace_archive(archive_path: str | Path) -> None:
    """Extract and execute the root calculation report from a v4 archive.

    Args:
        archive_path: PNG or UZC archive generated by UzonCalc.

    Returns:
        None.

    Raises:
        ValueError: If the executable manifest or entry path is invalid.
        ImportError: If the declared entry module cannot be imported.
        OSError: If the archive or extracted files cannot be read or written.
    """
    resolved_archive_path = Path(archive_path).resolve()
    archive = read_workspace_archive(resolved_archive_path.read_bytes())
    executable = archive.manifest.get("executable")
    if not isinstance(executable, dict):
        raise ValueError("归档缺少可执行入口声明")
    files_prefix = executable.get("filesPrefix")
    entry_path = executable.get("entryPath")
    auto_view_entry = executable.get("autoViewEntry")
    if not isinstance(files_prefix, str) or not files_prefix.endswith("/"):
        raise ValueError("归档可执行文件前缀无效")
    if not isinstance(entry_path, str) or not entry_path.endswith(".py"):
        raise ValueError("归档可执行入口无效")
    if auto_view_entry is not None and not isinstance(auto_view_entry, str):
        raise ValueError("归档自动运行入口无效")

    with tempfile.TemporaryDirectory(prefix="uzoncalc-v4-") as temp_dir:
        workspace_root = Path(temp_dir)
        _extract_executable_files(archive.files, files_prefix, workspace_root)
        root_node = _materialize_dependency_namespace(
            archive.manifest, archive.files, workspace_root
        )
        entry_file = (workspace_root / entry_path).resolve()
        try:
            entry_file.relative_to(workspace_root.resolve())
        except ValueError as error:
            raise ValueError("归档可执行入口越界") from error
        if not entry_file.is_file():
            raise ValueError("归档可执行入口不存在")
        if root_node is None:
            raise ValueError("归档缺少根报告声明")
        _run_workspace_entry(workspace_root, entry_file, auto_view_entry, root_node)


def _materialize_dependency_namespace(
    manifest: dict[str, Any], files: dict[str, bytes], workspace_root: Path
) -> dict[str, Any] | None:
    """Rebuild the scoped ``calcdeps`` namespace used by server execution.

    Args:
        manifest: Validated v4 archive manifest.
        files: Validated archive files.
        workspace_root: Extracted root report directory.

    Returns:
        Root report node when the report manifest exists, otherwise ``None``.

    Raises:
        ValueError: If report nodes or dependency selectors are incomplete.
        SyntaxError: If a bundled Python source cannot be rewritten.
        OSError: If dependency files cannot be materialized.
    """
    nodes = manifest.get("reports")
    if not isinstance(nodes, list):
        return None
    report_nodes: dict[str, list[dict[str, Any]]] = {}
    for node in nodes:
        if not isinstance(node, dict) or not isinstance(node.get("reportKey"), str):
            raise ValueError("归档依赖节点无效")
        report_nodes.setdefault(node["reportKey"], []).append(node)

    root_node_key = manifest.get("rootNodeKey")
    root_node = next(
        (node for node in nodes if node.get("nodeKey") == root_node_key), None
    )
    if root_node is not None:
        _rewrite_extracted_python_files(workspace_root, root_node)

    namespace_root = workspace_root / "__uzon_deps__"
    for owner_node in nodes:
        dependencies = owner_node.get("dependencies", [])
        if not isinstance(dependencies, list):
            raise ValueError("归档依赖声明无效")
        owner_scope = _archive_scope_key(owner_node)
        for dependency in dependencies:
            if not isinstance(dependency, dict):
                raise ValueError("归档依赖声明无效")
            alias = dependency.get("alias")
            target_report_key = dependency.get("targetReportOid")
            selectors = dependency.get("selectors")
            if (
                not isinstance(alias, str)
                or not alias.isidentifier()
                or not isinstance(target_report_key, str)
                or not isinstance(selectors, list)
            ):
                raise ValueError("归档依赖选择器无效")
            for selector in selectors:
                target_node = _resolve_dependency_node(
                    report_nodes.get(target_report_key, []), selector
                )
                selector_key = selector["selectorKey"]
                destination = namespace_root / owner_scope / alias / selector_key
                _write_dependency_node(files, target_node, destination)
                _create_package_markers(destination, workspace_root)
    return root_node


def _resolve_dependency_node(
    nodes: list[dict[str, Any]], selector: object
) -> dict[str, Any]:
    """Resolve one archived dependency version for a selector declaration.

    Args:
        nodes: Archived versions belonging to the target report.
        selector: Selector declaration from the owner artifact.

    Returns:
        Matching archived report node.

    Raises:
        ValueError: If selector metadata or the selected version is missing.
    """
    if not isinstance(selector, dict) or not isinstance(
        selector.get("selectorKey"), str
    ):
        raise ValueError("归档依赖选择器无效")
    version_name = selector.get("versionName")
    if version_name is None:
        target = next((node for node in nodes if node.get("isLatest") is True), None)
    else:
        target = next(
            (node for node in nodes if node.get("versionName") == version_name), None
        )
    if target is None:
        raise ValueError("归档依赖版本不完整")
    return target


def _write_dependency_node(
    files: dict[str, bytes], node: dict[str, Any], destination: Path
) -> None:
    """Materialize one dependency component with scoped import rewriting.

    Args:
        files: Validated archive files.
        node: Selected dependency report node.
        destination: Scoped component directory.

    Returns:
        None.

    Raises:
        ValueError: If the node file prefix is invalid.
        SyntaxError: If Python source rewriting fails.
        OSError: If a component file cannot be written.
    """
    prefix = node.get("filesPrefix")
    if not isinstance(prefix, str) or not prefix.endswith("/"):
        raise ValueError("归档依赖文件前缀无效")
    for archive_name, content in files.items():
        if not archive_name.startswith(prefix):
            continue
        relative_path = archive_name.removeprefix(prefix)
        target = destination / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    _rewrite_extracted_python_files(destination, node)


def _rewrite_extracted_python_files(source_root: Path, node: dict[str, Any]) -> None:
    """Normalize local and calcdeps imports in one extracted report source tree.

    Args:
        source_root: Extracted ``src`` directory.
        node: Report node owning the source tree.

    Returns:
        None.

    Raises:
        SyntaxError: If Python parsing or rewriting fails.
        OSError: If rewritten source cannot be read or written.
    """
    source_paths = sorted(source_root.rglob("*.py"))
    import_roots = workspace_import_roots(
        source_path.relative_to(source_root).as_posix()
        for source_path in source_paths
    )
    for source_path in source_paths:
        relative_path = source_path.relative_to(source_root).as_posix()
        source_path.write_bytes(
            _rewrite_python_content(
                source_path.read_bytes(),
                node,
                source_path=relative_path,
                import_roots=import_roots,
            )
        )


def _rewrite_python_content(
    content: bytes,
    node: dict[str, Any],
    *,
    source_path: str,
    import_roots: frozenset[str],
) -> bytes:
    """Apply workspace-relative and scoped calcdeps imports to Python bytes.

    Args:
        content: UTF-8 Python source.
        node: Report node containing dependency declarations and artifact hash.
        source_path: Report-root-relative source path.
        import_roots: Top-level Python modules owned by the report.

    Returns:
        Rewritten UTF-8 source.

    Raises:
        UnicodeDecodeError: If source is not UTF-8.
        SyntaxError: If source parsing fails.
        ValueError: If dependency defaults are invalid.
    """
    source = rewrite_workspace_source(
        content.decode("utf-8"),
        source_path=source_path,
        import_roots=import_roots,
    )
    dependencies = node.get("dependencies", [])
    if not dependencies:
        return source.encode("utf-8")
    defaults: dict[str, str] = {}
    for dependency in dependencies:
        default_selector = next(
            (
                selector
                for selector in dependency.get("selectors", [])
                if selector.get("isDefault") is True
            ),
            None,
        )
        if default_selector is None:
            raise ValueError("归档依赖缺少默认选择器")
        defaults[dependency["alias"]] = default_selector["selectorKey"]
    syntax_tree = ast.parse(source)
    rewritten = _CalcdepsImportRewriter(_archive_scope_key(node), defaults).visit(
        syntax_tree
    )
    ast.fix_missing_locations(rewritten)
    return (ast.unparse(rewritten) + "\n").encode("utf-8")


def _archive_scope_key(node: dict[str, Any]) -> str:
    """Return the same valid scope key used by execution bundles.

    Args:
        node: Archived report node with an artifact hash.

    Returns:
        Python identifier namespace for that artifact.

    Raises:
        ValueError: If the artifact hash is absent or malformed.
    """
    artifact_hash = node.get("artifactHash")
    if not isinstance(artifact_hash, str) or len(artifact_hash) < 16:
        raise ValueError("归档报告缺少有效的 artifactHash")
    return f"scope_{artifact_hash[:16]}"


def _create_package_markers(destination: Path, root: Path) -> None:
    """Create package markers from a component directory to its bundle root.

    Args:
        destination: Deep dependency component directory.
        root: Temporary bundle root excluded from marker creation.

    Returns:
        None.

    Raises:
        OSError: If a package directory or marker cannot be created.
    """
    current = destination
    while current != root:
        current.mkdir(parents=True, exist_ok=True)
        current.joinpath("__init__.py").touch(exist_ok=True)
        current = current.parent


def _extract_executable_files(
    files: dict[str, bytes], files_prefix: str, workspace_root: Path
) -> None:
    """Materialize files belonging to the executable root report.

    Args:
        files: Validated archive files.
        files_prefix: Prefix identifying the root report files.
        workspace_root: Empty temporary extraction root.

    Returns:
        None.

    Raises:
        ValueError: If no executable files are present.
        OSError: If an extracted file cannot be written.
    """
    extracted_count = 0
    for archive_name, content in files.items():
        if archive_name == ARCHIVE_MAIN_PATH or not archive_name.startswith(
            files_prefix
        ):
            continue
        relative_path = archive_name.removeprefix(files_prefix)
        destination = workspace_root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(content)
        extracted_count += 1
    if extracted_count == 0:
        raise ValueError("归档可执行文件为空")


def _run_workspace_entry(
    workspace_root: Path,
    entry_file: Path,
    auto_view_entry: str | None,
    root_node: dict[str, Any],
) -> None:
    """Run one extracted entry with package-aware Python import semantics.

    Args:
        workspace_root: Extracted root-package report directory.
        entry_file: Absolute Python entry path.
        auto_view_entry: Explicit decorated function name, when known.
        root_node: Root report manifest node providing an isolated identity.

    Returns:
        None.

    Raises:
        ValueError: If no decorated calculation entry can be selected.
        ImportError: If the entry module or one of its imports fails.
    """
    try:
        module_relative_path = entry_file.relative_to(workspace_root).with_suffix("")
    except ValueError as error:
        raise ValueError("归档入口必须位于工作区根目录内") from error
    module_parts = list(module_relative_path.parts)
    if module_parts[-1] == "__init__":
        module_parts = module_parts[:-1]
    if not all(part.isidentifier() for part in module_parts):
        raise ValueError("归档入口不能转换为 Python 模块名")
    package_name = f"__uzon_workspace_{root_node['artifactHash'][:16]}"
    module_name = ".".join([package_name, *module_parts])

    replaced_private_modules = _install_archive_runtime_packages(workspace_root)
    try:
        _install_archive_workspace_package(workspace_root, package_name)
        if module_name != package_name:
            sys.modules.pop(module_name, None)
        if auto_view_entry is None:
            runpy.run_module(module_name, run_name="__main__", alter_sys=True)
            return
        module = (
            sys.modules[package_name]
            if module_name == package_name
            else importlib.import_module(module_name)
        )
        view(_resolve_named_entry(module, auto_view_entry))
    finally:
        _restore_archive_import_environment(
            package_name,
            replaced_private_modules,
        )


def _install_archive_workspace_package(
    workspace_root: Path, package_name: str
) -> None:
    """Load the extracted root ``__init__.py`` under an isolated package name.

    Args:
        workspace_root: Extracted root-package directory.
        package_name: Collision-resistant synthetic package name.

    Returns:
        None.

    Raises:
        ImportError: If the root package marker cannot be loaded.
    """
    init_path = workspace_root / "__init__.py"
    spec = importlib.util.spec_from_file_location(
        package_name,
        init_path,
        submodule_search_locations=[str(workspace_root)],
    )
    if spec is None or spec.loader is None:
        raise ImportError("无法加载归档工作区根包")
    package = importlib.util.module_from_spec(spec)
    sys.modules[package_name] = package
    spec.loader.exec_module(package)


def _install_archive_runtime_packages(
    workspace_root: Path,
) -> dict[str, ModuleType]:
    """Install private dependency packages without changing ``sys.path``.

    Args:
        workspace_root: Extracted archive workspace containing private packages.

    Returns:
        Previous private modules to restore after execution.

    Raises:
        ImportError: If a present private package cannot be loaded.
    """
    package_name = "__uzon_deps__"
    init_path = workspace_root / package_name / "__init__.py"
    if not init_path.is_file():
        return {}
    replaced: dict[str, ModuleType] = {}
    package_prefix = f"{package_name}."
    for module_name in list(sys.modules):
        if module_name != package_name and not module_name.startswith(package_prefix):
            continue
        module = sys.modules.pop(module_name, None)
        if module is not None:
            replaced[module_name] = module
    spec = importlib.util.spec_from_file_location(
        package_name,
        init_path,
        submodule_search_locations=[str(init_path.parent)],
    )
    if spec is None or spec.loader is None:
        sys.modules.update(replaced)
        raise ImportError("无法加载归档私有依赖包")
    package = importlib.util.module_from_spec(spec)
    sys.modules[package_name] = package
    try:
        spec.loader.exec_module(package)
    except Exception:
        # 私有包初始化失败时，还原进程在运行前的模块状态。
        for module_name in list(sys.modules):
            if module_name == package_name or module_name.startswith(package_prefix):
                sys.modules.pop(module_name, None)
        sys.modules.update(replaced)
        raise
    return replaced


def _restore_archive_import_environment(
    package_name: str,
    replaced_private_modules: dict[str, ModuleType],
) -> None:
    """Remove archive-private modules and restore previous private state.

    Args:
        package_name: Synthetic package name used for execution.
        replaced_private_modules: Previous private dependency modules.

    Returns:
        None.

    Raises:
        None.
    """
    package_prefix = f"{package_name}."
    for module_name in list(sys.modules):
        if (
            module_name == package_name
            or module_name.startswith(package_prefix)
            or module_name == "__uzon_deps__"
            or module_name.startswith("__uzon_deps__.")
        ):
            sys.modules.pop(module_name, None)
    sys.modules.update(replaced_private_modules)


def _resolve_named_entry(module: ModuleType, entry_name: str):
    """Resolve and validate one named decorated calculation entry.

    Args:
        module: Imported workspace entry module.
        entry_name: Function name declared by archive metadata.

    Returns:
        Decorated callable accepted by :func:`uzoncalc.view`.

    Raises:
        ValueError: If the named value is absent or not decorated.
    """
    entry = getattr(module, entry_name, None)
    if not callable(entry) or not getattr(entry, "_uzon_calc_entry", False):
        raise ValueError("归档自动运行入口不是 @uzon_calc 函数")
    return entry
