from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tomllib
import zipfile
from datetime import datetime, timedelta
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent


class BuildError(RuntimeError):
    pass


def write_info(message: str) -> None:
    print(f"[INFO] {message}")


def write_step(message: str) -> None:
    print()
    print("========================================")
    print(message)
    print("========================================")


def resolve_repo_path(relative_path: str) -> Path:
    return (REPO_ROOT / relative_path).resolve()


def resolve_output_path(output_dir: str | None, version: str) -> Path:
    if not output_dir or not output_dir.strip():
        return resolve_repo_path(f"dist/uzoncalc-win-x64-{version}")

    output_path = Path(output_dir)
    if output_path.is_absolute():
        return output_path.resolve()
    return (REPO_ROOT / output_path).resolve()


def assert_path_exists(path: Path, description: str) -> None:
    if not path.exists():
        raise BuildError(f"{description} does not exist: {path}")


def assert_is_inside_path(path: Path, parent_path: Path) -> None:
    full_path = path.resolve()
    full_parent_path = parent_path.resolve()
    try:
        full_path.relative_to(full_parent_path)
    except ValueError as exc:
        raise BuildError(f"Output path must be inside the repository: {full_path}") from exc
    if full_path == full_parent_path:
        raise BuildError(f"Output path must be inside the repository: {full_path}")


def run_command(command: list[str], *, cwd: Path, failure_message: str) -> None:
    completed = subprocess.run(command, cwd=cwd, check=False)
    if completed.returncode != 0:
        raise BuildError(f"{failure_message}, exit code: {completed.returncode}")


def copy_directory_contents(source: Path, destination: Path) -> None:
    assert_path_exists(source, "Source directory")
    destination.mkdir(parents=True, exist_ok=True)
    for item in source.iterdir():
        target = destination / item.name
        if item.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)


def resolve_archive_path(output_directory: Path) -> Path:
    return output_directory.with_suffix(".zip")


def get_cargo_package_version(manifest_path: Path) -> str:
    assert_path_exists(manifest_path, "Rust Cargo.toml")
    with manifest_path.open("rb") as manifest_file:
        manifest = tomllib.load(manifest_file)
    try:
        version = manifest["package"]["version"]
    except KeyError as exc:
        raise BuildError(f"Rust package version was not found: {manifest_path}") from exc
    if not isinstance(version, str) or not version:
        raise BuildError(f"Rust package version is invalid: {manifest_path}")
    return version


def get_latest_release_exe(release_directory: Path, build_started_at: datetime) -> Path:
    assert_path_exists(release_directory, "Tauri release directory")
    earliest_timestamp = (build_started_at - timedelta(seconds=5)).timestamp()
    exe_files = [
        path
        for path in release_directory.glob("*.exe")
        if path.is_file() and path.stat().st_mtime >= earliest_timestamp
    ]
    if not exe_files:
        raise BuildError(f"No exe generated by this Tauri build: {release_directory}")
    return max(exe_files, key=lambda path: path.stat().st_mtime).resolve()


def directory_size_mb(directory: Path) -> float:
    total_size = sum(path.stat().st_size for path in directory.rglob("*") if path.is_file())
    return total_size / 1024 / 1024


def create_zip_from_directory(source_directory: Path, archive_path: Path) -> None:
    archive_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(source_directory.rglob("*")):
            archive.write(path, path.relative_to(source_directory.parent))


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the Windows desktop package.")
    parser.add_argument("--output-dir", dest="output_dir")
    parser.add_argument("--api-output-name", default="UzonCalc-Portable")
    parser.add_argument("--python-version", default="3.13.14")
    parser.add_argument("--python-cache-root")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    web_dir = resolve_repo_path("src/web")
    tauri_dir = resolve_repo_path("src/web/src-tauri")
    node_modules_dir = web_dir / "node_modules"
    icon_ico_path = tauri_dir / "icons/icon.ico"
    icon_source_path = web_dir / "public/icons/favicon.svg"
    api_dir = resolve_repo_path("src/api")
    api_build_script = api_dir / "scripts/build-portable.py"
    api_portable_dir = api_dir / "dist" / args.api_output_name
    release_dir = tauri_dir / "target/release"
    release_config = release_dir / "config.toml"
    source_config = tauri_dir / "config.toml"
    cargo_manifest = tauri_dir / "Cargo.toml"
    app_version = get_cargo_package_version(cargo_manifest)
    resolved_output_dir = resolve_output_path(args.output_dir, app_version)
    archive_path = resolve_archive_path(resolved_output_dir)

    assert_is_inside_path(resolved_output_dir, REPO_ROOT)
    assert_is_inside_path(archive_path, REPO_ROOT)
    assert_path_exists(web_dir, "Web directory")
    assert_path_exists(tauri_dir, "Tauri directory")
    assert_path_exists(api_build_script, "API build script")

    write_step("Prepare Tauri desktop")
    write_info(f"Web directory: {web_dir}")

    if shutil.which("cargo") is None:
        raise BuildError("cargo was not found. Install the Rust toolchain first.")

    if not node_modules_dir.exists():
        if shutil.which("bun") is None:
            raise BuildError("bun was not found. Install Bun first.")
        write_info("node_modules was not found. Installing Web dependencies.")
        run_command(["bun", "install"], cwd=web_dir, failure_message="Web dependency installation failed")
    else:
        write_info("node_modules found. Skipping Web dependency installation.")

    if not icon_ico_path.exists():
        assert_path_exists(icon_source_path, "Tauri icon source")
        write_info("icon.ico was not found. Generating Tauri icons.")
        run_command(
            ["cargo", "tauri", "icon", "../public/icons/favicon.svg"],
            cwd=tauri_dir,
            failure_message="Tauri icon generation failed",
        )
    else:
        write_info("icon.ico found. Skipping Tauri icon generation.")

    write_step("Build Tauri desktop")
    tauri_build_started_at = datetime.now()
    run_command(
        ["cargo", "tauri", "build", "--no-bundle"],
        cwd=web_dir,
        failure_message="Tauri build failed",
    )
    desktop_exe = get_latest_release_exe(release_dir, tauri_build_started_at)

    write_step("Build API portable package")
    write_info(f"API build script: {api_build_script}")
    api_build_args = [
        sys.executable,
        str(api_build_script),
        "--output-name",
        args.api_output_name,
        "--python-version",
        args.python_version,
    ]
    if args.python_cache_root and args.python_cache_root.strip():
        api_build_args.extend(["--python-cache-root", args.python_cache_root])
    run_command(api_build_args, cwd=REPO_ROOT, failure_message="API portable package build failed")
    assert_path_exists(api_portable_dir, "API portable package output directory")

    write_step("Collect package files")
    write_info(f"Output directory: {resolved_output_dir}")

    if resolved_output_dir.exists():
        shutil.rmtree(resolved_output_dir)
    resolved_output_dir.mkdir(parents=True, exist_ok=True)

    write_info(f"Copy desktop executable: {desktop_exe}")
    shutil.copy2(desktop_exe, resolved_output_dir)

    if release_config.exists():
        write_info(f"Copy config: {release_config}")
        shutil.copy2(release_config, resolved_output_dir)
    else:
        assert_path_exists(source_config, "Tauri config file")
        write_info(f"Copy config: {source_config}")
        shutil.copy2(source_config, resolved_output_dir)

    write_info(f"Copy API portable package: {api_portable_dir}")
    copy_directory_contents(api_portable_dir, resolved_output_dir)
    total_size = directory_size_mb(resolved_output_dir)

    write_step("Create zip archive")
    write_info(f"zip file: {archive_path}")
    if archive_path.exists():
        archive_path.unlink()
    create_zip_from_directory(resolved_output_dir, archive_path)
    archive_size = archive_path.stat().st_size / 1024 / 1024

    write_step("Upload zip archive")
    if shutil.which("onedo"):
        write_info(f"onedo detected. Uploading: {archive_path}")
        run_command(["onedo", "minio", "soft", "-p", str(archive_path)], cwd=REPO_ROOT, failure_message="zip upload failed")
        write_info("zip upload complete.")
    else:
        write_info("onedo was not found. Skipping upload.")

    write_step("Build complete")
    write_info(f"Package directory: {resolved_output_dir}")
    write_info(f"Total size: {total_size:.2f} MB")
    write_info(f"zip file: {archive_path}")
    write_info(f"zip size: {archive_size:.2f} MB")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print()
        print("[WARN] Build cancelled.")
        raise SystemExit(130)
    except BuildError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        raise SystemExit(1)
