services:
  uzoncalc-dev:
    container_name: uzoncalc-dev
    image: node:20.11.0
    volumes:
      - ./:/app/uzoncalc
    working_dir: /app/uzoncalc
    ports:
      - 9000:9000
    init: true
    command: [ "sh", "-c", "exec sleep infinity" ]
